In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/aizazafridi/logistics-transportation/logistics_transportation.db

In [4]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [5]:
database = '/kaggle/input/datasets/aizazafridi/logistics-transportation/logistics_transportation.db'

In [6]:
conn = sqlite3.connect(database )

In [7]:
# Data Import: db file to pandas, storing each table to a separate df

# Connect to SQLite database
conn = sqlite3.connect(database)

# sql query to Get all table names
sql_query = """
        SELECT name
        FROM sqlite_master
        WHERE type='table';
"""

# read sql query in pandas
tables = pd.read_sql(sql_query, conn)

# create dataframe for each table
for table_name in tables['name']:
    df = pd.read_sql(f"SELECT * FROM {table_name}", conn) # Read table into dataframe
    globals()[f"df_{table_name}"] = df                    # Create dynamic dataframe name
    print(f"Created dataframe: df_{table_name}")

# Close connection
conn.close()

Created dataframe: df_customers
Created dataframe: df_branches
Created dataframe: df_vehicle_types
Created dataframe: df_drivers
Created dataframe: df_vehicles
Created dataframe: df_routes
Created dataframe: df_shipments
Created dataframe: df_delivery_events
Created dataframe: df_trips
Created dataframe: df_fuel_transactions
Created dataframe: df_maintenance
Created dataframe: df_customer_feedback
Created dataframe: df_monthly_kpis

In [8]:
# Print table names and column names
conn = sqlite3.connect(database)

for table_name in tables['name']:
    print(f"\nTable Name: {table_name}")
    # Get column information
    columns_query = f"PRAGMA table_info({table_name});"
    columns = pd.read_sql(columns_query, conn)
    print("Columns:")
    print(columns['name'].tolist())

# Close connection
conn.close()

Table Name: customers
Columns:
['customer_id', 'customer_name', 'industry']

Table Name: branches
Columns:
['branch_id', 'branch_name', 'city']

Table Name: vehicle_types
Columns:
['vehicle_type_id', 'vehicle_type', 'category', 'capacity_kg']

Table Name: drivers
Columns:
['driver_id', 'driver_name', 'mobile', 'license_no', 'employment_type', 'base_city', 'status']

Table Name: vehicles
Columns:
['vehicle_id', 'plate_no', 'vehicle_type_id', 'base_city', 'model_year', 'ownership', 'status']

Table Name: routes
Columns:
['route_id', 'route_name', 'origin_city', 'destination_city', 'distance_km', 'planned_minutes']

Table Name: shipments
Columns:
['shipment_id', 'order_id', 'customer_id', 'service_type', 'branch_id', 'route_id', 'order_datetime', 'promised_datetime', 'actual_delivery_datetime', 'status', 'weight_kg', 'distance_km', 'payment_method', 'delivery_revenue', 'priority', 'month']

Table Name: delivery_events
Columns:
['event_id', 'shipment_id', 'event_datetime', 'event_type', 'location_city', 'handling_time_min', 'recorded_by']

Table Name: trips
Columns:
['trip_id', 'vehicle_id', 'driver_id', 'route_id', 'departure_time', 'arrival_time', 'stops_count', 'shipments_count', 'fuel_liters', 'trip_status']

Table Name: fuel_transactions
Columns:
['fuel_id', 'vehicle_id', 'fuel_datetime', 'liters', 'price_per_liter', 'total_cost', 'fuel_type', 'city']

Table Name: maintenance
Columns:
['maintenance_id', 'vehicle_id', 'maintenance_date', 'maintenance_type', 'cost', 'status', 'odometer_km']

Table Name: customer_feedback
Columns:
['feedback_id', 'shipment_id', 'rating', 'feedback_category', 'customer_comment']

Table Name: monthly_kpis
Columns:
['month', 'service_type', 'total_shipments', 'delivered_shipments', 'total_revenue', 'avg_weight_kg', 'avg_distance_km', 'delivery_success_rate_pct']

In [9]:
df_customers.head(100)

   customer_id        customer_name    industry
0      CUST001                 Noon  E-Commerce
1      CUST002         Amazon Saudi  E-Commerce
2      CUST003      Jarir Bookstore      Retail
3      CUST004         Extra Stores      Retail
4      CUST005        Nahdi Medical  Healthcare
5      CUST006  Al-Dawaa Pharmacies  Healthcare
6      CUST007                 SACO      Retail
7      CUST008               Danube      Retail
8      CUST009     Lulu Hypermarket      Retail
9      CUST010            BinDawood      Retail
10     CUST011                Jahez  E-Commerce
11     CUST012        HungerStation  E-Commerce
12     CUST013     Al Habib Medical  Healthcare
13     CUST014          Fakeeh Care  Healthcare
14     CUST015               Careem  E-Commerce

In [10]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    15 non-null     object
 1   customer_name  15 non-null     object
 2   industry       15 non-null     object
dtypes: object(3)
memory usage: 492.0+ bytes

In [11]:
df_branches

  branch_id     branch_name     city
0     BR001  Riyadh Central   Riyadh
1     BR002      Jeddah Hub   Jeddah
2     BR003      Dammam Hub   Dammam
3     BR004     Madinah Hub  Madinah
4     BR005      Makkah Hub   Makkah
5     BR006        Abha Hub     Abha

In [12]:
df_branches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   branch_id    6 non-null      object
 1   branch_name  6 non-null      object
 2   city         6 non-null      object
dtypes: object(3)
memory usage: 276.0+ bytes

In [13]:
df_vehicle_types

  vehicle_type_id        vehicle_type                category  capacity_kg
0            VT01          Motorcycle             Two Wheeler           15
1            VT02                 Van        Light Commercial          800
2            VT03    Refrigerated Van  Temperature Controlled          700
3            VT04           Box Truck            Medium Truck         3500
4            VT05  Refrigerated Truck  Temperature Controlled         5000
5            VT06         Heavy Truck             Heavy Truck        12000

In [14]:
df_drivers

,driver_id,driver_name,mobile,license_no,employment_type,base_city,status
0,DRV001,Omar Khan,+966546913810,DL-356787,Full Time,Abha,Active
1,DRV002,Omar Aziz,+966583197857,DL-191161,Contract,Abha,Active
2,DRV003,Abdullah Hassan,+966541227216,DL-629903,Full Time,Riyadh,Active
3,DRV004,Sami Iqbal,+966539587039,DL-571029,Contract,Abha,Active
4,DRV005,Tariq Malik,+966547295260,DL-263032,Full Time,Jeddah,Active
...,...,...,...,...,...,...,...
115,DRV116,Yousef Malik,+966534084236,DL-416950,Full Time,Dammam,Active
116,DRV117,Mohammed Khan,+966584270583,DL-406327,Full Time,Dammam,On Leave
117,DRV118,Ahmed Saeed,+966548163378,DL-592198,Contract,Riyadh,On Leave
118,DRV119,Saad Khan,+966543887075,DL-600935,Full Time,Dammam,Active
119,DRV120,Bader Ali,+966587446468,DL-760021,Full Time,Madinah,Active

In [15]:
df_drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   driver_id        120 non-null    object
 1   driver_name      120 non-null    object
 2   mobile           120 non-null    object
 3   license_no       120 non-null    object
 4   employment_type  120 non-null    object
 5   base_city        120 non-null    object
 6   status           120 non-null    object
dtypes: object(7)
memory usage: 6.7+ KB

In [16]:
df_customers.info()
df_branches.info()
df_vehicle_types.info()
df_drivers.info()
df_vehicles.info()
df_routes.info()
df_shipments.info()
df_delivery_events.info()
df_trips.info()
df_fuel_transactions.info()
df_maintenance.info()
df_customer_feedback.info()
df_monthly_kpis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    15 non-null     object
 1   customer_name  15 non-null     object
 2   industry       15 non-null     object
dtypes: object(3)
memory usage: 492.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   branch_id    6 non-null      object
 1   branch_name  6 non-null      object
 2   city         6 non-null      object
dtypes: object(3)
memory usage: 276.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   vehicle_type_id  6 non-null      object
 1   vehicle_type     6 non-null      object
 2   category         6 non-null      object
 3   capacity_kg      6 non-null      int64
dtypes: int64(1), object(3)
memory usage: 324.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   driver_id        120 non-null    object
 1   driver_name      120 non-null    object
 2   mobile           120 non-null    object
 3   license_no       120 non-null    object
 4   employment_type  120 non-null    object
 5   base_city        120 non-null    object
 6   status           120 non-null    object
dtypes: object(7)
memory usage: 6.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   vehicle_id       150 non-null    object
 1   plate_no         150 non-null    object
 2   vehicle_type_id  150 non-null    object
 3   base_city        150 non-null    object
 4   model_year       150 non-null    int64
 5   ownership        150 non-null    object
 6   status           150 non-null    object
dtypes: int64(1), object(6)
memory usage: 8.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   route_id          100 non-null    object
 1   route_name        100 non-null    object
 2   origin_city       100 non-null    object
 3   destination_city  100 non-null    object
 4   distance_km       100 non-null    int64
 5   planned_minutes   100 non-null    int64
dtypes: int64(2), object(4)
memory usage: 4.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   shipment_id               1000 non-null   object
 1   order_id                  1000 non-null   object
 2   customer_id               1000 non-null   object
 3   service_type              1000 non-null   object
 4   branch_id                 1000 non-null   object
 5   route_id                  1000 non-null   object
 6   order_datetime            1000 non-null   object
 7   promised_datetime         1000 non-null   object
 8   actual_delivery_datetime  833 non-null    object
 9   status                    1000 non-null   object
 10  weight_kg                 1000 non-null   float64
 11  distance_km               1000 non-null   int64
 12  payment_method            1000 non-null   object
 13  delivery_revenue          1000 non-null   float64
 14  priority                  1000 non-null   object
 15  month                     1000 non-null   object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   event_id           1000 non-null   object
 1   shipment_id        1000 non-null   object
 2   event_datetime     1000 non-null   object
 3   event_type         1000 non-null   object
 4   location_city      1000 non-null   object
 5   handling_time_min  1000 non-null   float64
 6   recorded_by        1000 non-null   object
dtypes: float64(1), object(6)
memory usage: 54.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   trip_id          1000 non-null   object
 1   vehicle_id       1000 non-null   object
 2   driver_id        1000 non-null   object
 3   route_id         1000 non-null   object
 4   departure_time   1000 non-null   object
 5   arrival_time     1000 non-null   object
 6   stops_count      1000 non-null   int64
 7   shipments_count  1000 non-null   int64
 8   fuel_liters      1000 non-null   float64
 9   trip_status      1000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fuel_id          1000 non-null   object
 1   vehicle_id       1000 non-null   object
 2   fuel_datetime    1000 non-null   object
 3   liters           1000 non-null   float64
 4   price_per_liter  1000 non-null   float64
 5   total_cost       1000 non-null   float64
 6   fuel_type        1000 non-null   object
 7   city             1000 non-null   object
dtypes: float64(3), object(5)
memory usage: 62.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   maintenance_id    500 non-null    object
 1   vehicle_id        500 non-null    object
 2   maintenance_date  500 non-null    object
 3   maintenance_type  500 non-null    object
 4   cost              500 non-null    float64
 5   status            500 non-null    object
 6   odometer_km       500 non-null    int64
dtypes: float64(1), int64(1), object(5)
memory usage: 27.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feedback_id        500 non-null    object
 1   shipment_id        500 non-null    object
 2   rating             500 non-null    int64
 3   feedback_category  500 non-null    object
 4   customer_comment   500 non-null    object
dtypes: int64(1), object(4)
memory usage: 19.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      24 non-null     object
 1   service_type               24 non-null     object
 2   total_shipments            24 non-null     int64
 3   delivered_shipments        24 non-null     int64
 4   total_revenue              24 non-null     float64
 5   avg_weight_kg              24 non-null     float64
 6   avg_distance_km            24 non-null     float64
 7   delivery_success_rate_pct  24 non-null     float64
dtypes: float64(4), int64(2), object(2)
memory usage: 1.6+ KB

# Create the main shipment fact table

In [17]:
fact_shipments = (
    df_shipments
    .merge(
        df_customers,
        on="customer_id",
        how="left"
    )
    .merge(
        df_branches,
        on="branch_id",
        how="left"
    )
    .merge(
        df_routes,
        on="route_id",
        how="left"
    )
)

In [18]:
fact_shipments

,shipment_id,order_id,customer_id,service_type,branch_id,route_id,order_datetime,promised_datetime,actual_delivery_datetime,status,...,month,customer_name,industry,branch_name,city,route_name,origin_city,destination_city,distance_km_y,planned_minutes
0,SHP00001,ORD00001,CUST008,Retail,BR004,RT017,2026-01-30 21:13:00,2026-02-02 21:13:00,2026-02-03 19:13:00,Delivered,...,2026-01,Danube,Retail,Madinah Hub,Madinah,Jeddah North,Jeddah,Abha,617,78
1,SHP00002,ORD00002,CUST008,Retail,BR001,RT006,2026-06-22 09:46:00,2026-06-22 21:46:00,2026-06-22 11:46:00,Delivered,...,2026-06,Danube,Retail,Riyadh Central,Riyadh,Riyadh South,Makkah,Dammam,380,118
2,SHP00003,ORD00003,CUST001,E-Commerce,BR006,RT094,2026-08-28 02:59:00,2026-08-30 02:59:00,2026-08-30 18:59:00,Delivered,...,2026-08,Noon,E-Commerce,Abha Hub,Abha,Riyadh-Jeddah,Jeddah,Madinah,773,73
3,SHP00004,ORD00004,CUST008,Retail,BR006,RT045,2026-08-11 12:24:00,2026-08-12 00:24:00,2026-08-13 08:24:00,Delivered,...,2026-08,Danube,Retail,Abha Hub,Abha,Makkah Central,Madinah,Abha,621,80
4,SHP00005,ORD00005,CUST009,Retail,BR006,RT093,2026-02-02 23:14:00,2026-02-03 11:14:00,None,In Transit,...,2026-02,Lulu Hypermarket,Retail,Abha Hub,Abha,Riyadh East,Makkah,Jeddah,281,81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,SHP00996,ORD00996,CUST012,E-Commerce,BR002,RT032,2026-02-19 04:20:00,2026-02-22 04:20:00,2026-02-22 08:20:00,Returned,...,2026-02,HungerStation,E-Commerce,Jeddah Hub,Jeddah,Riyadh-Jeddah,Jeddah,Dammam,757,117
996,SHP00997,ORD00997,CUST006,Healthcare,BR005,RT094,2026-05-11 03:24:00,2026-05-12 03:24:00,2026-05-11 22:24:00,Delivered,...,2026-05,Al-Dawaa Pharmacies,Healthcare,Makkah Hub,Makkah,Riyadh-Jeddah,Jeddah,Madinah,773,73
997,SHP00998,ORD00998,CUST013,Healthcare,BR006,RT001,2026-07-17 08:45:00,2026-07-18 08:45:00,2026-07-18 01:45:00,Delivered,...,2026-07,Al Habib Medical,Healthcare,Abha Hub,Abha,Riyadh Central,Jeddah,Madinah,747,90
998,SHP00999,ORD00999,CUST009,Retail,BR006,RT025,2026-02-07 08:20:00,2026-02-09 08:20:00,2026-02-10 12:20:00,Returned,...,2026-02,Lulu Hypermarket,Retail,Abha Hub,Abha,Jeddah Central,Makkah,Abha,396,117
999,SHP01000,ORD01000,CUST015,E-Commerce,BR001,RT039,2026-02-19 16:51:00,2026-02-22 16:51:00,2026-02-23 06:51:00,Delivered,...,2026-02,Careem,E-Commerce,Riyadh Central,Riyadh,Riyadh Central,Makkah,Riyadh,87,37

In [19]:
fact_shipments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   shipment_id               1000 non-null   object
 1   order_id                  1000 non-null   object
 2   customer_id               1000 non-null   object
 3   service_type              1000 non-null   object
 4   branch_id                 1000 non-null   object
 5   route_id                  1000 non-null   object
 6   order_datetime            1000 non-null   object
 7   promised_datetime         1000 non-null   object
 8   actual_delivery_datetime  833 non-null    object
 9   status                    1000 non-null   object
 10  weight_kg                 1000 non-null   float64
 11  distance_km_x             1000 non-null   int64
 12  payment_method            1000 non-null   object
 13  delivery_revenue          1000 non-null   float64
 14  priority                  1000 non-null   object
 15  month                     1000 non-null   object
 16  customer_name             1000 non-null   object
 17  industry                  1000 non-null   object
 18  branch_name               1000 non-null   object
 19  city                      1000 non-null   object
 20  route_name                1000 non-null   object
 21  origin_city               1000 non-null   object
 22  destination_city          1000 non-null   object
 23  distance_km_y             1000 non-null   int64
 24  planned_minutes           1000 non-null   int64
dtypes: float64(2), int64(3), object(20)
memory usage: 195.4+ KB

#  Feature Engineering & Data Analysis

In [20]:
date_columns = [
    "order_datetime",
    "promised_datetime",
    "actual_delivery_datetime"
]

for col in date_columns:
    fact_shipments[col] = pd.to_datetime(
        fact_shipments[col],
        errors="coerce"
    )

In [21]:
fact_shipments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   shipment_id               1000 non-null   object
 1   order_id                  1000 non-null   object
 2   customer_id               1000 non-null   object
 3   service_type              1000 non-null   object
 4   branch_id                 1000 non-null   object
 5   route_id                  1000 non-null   object
 6   order_datetime            1000 non-null   datetime64[ns]
 7   promised_datetime         1000 non-null   datetime64[ns]
 8   actual_delivery_datetime  833 non-null    datetime64[ns]
 9   status                    1000 non-null   object
 10  weight_kg                 1000 non-null   float64
 11  distance_km_x             1000 non-null   int64
 12  payment_method            1000 non-null   object
 13  delivery_revenue          1000 non-null   float64
 14  priority                  1000 non-null   object
 15  month                     1000 non-null   object
 16  customer_name             1000 non-null   object
 17  industry                  1000 non-null   object
 18  branch_name               1000 non-null   object
 19  city                      1000 non-null   object
 20  route_name                1000 non-null   object
 21  origin_city               1000 non-null   object
 22  destination_city          1000 non-null   object
 23  distance_km_y             1000 non-null   int64
 24  planned_minutes           1000 non-null   int64
dtypes: datetime64[ns](3), float64(2), int64(3), object(17)
memory usage: 195.4+ KB

# delivery performance measures

In [22]:
print(fact_shipments[["order_datetime","actual_delivery_datetime"]])

         order_datetime actual_delivery_datetime
0   2026-01-30 21:13:00      2026-02-03 19:13:00
1   2026-06-22 09:46:00      2026-06-22 11:46:00
2   2026-08-28 02:59:00      2026-08-30 18:59:00
3   2026-08-11 12:24:00      2026-08-13 08:24:00
4   2026-02-02 23:14:00                      NaT
..                  ...                      ...
995 2026-02-19 04:20:00      2026-02-22 08:20:00
996 2026-05-11 03:24:00      2026-05-11 22:24:00
997 2026-07-17 08:45:00      2026-07-18 01:45:00
998 2026-02-07 08:20:00      2026-02-10 12:20:00
999 2026-02-19 16:51:00      2026-02-23 06:51:00

[1000 rows x 2 columns]

In [23]:
# Then calculate delivery time:


fact_shipments["delivery_time_minuts"] = (
    fact_shipments["actual_delivery_datetime"]
    - fact_shipments["order_datetime"]
).dt.total_seconds() / 60

In [24]:
fact_shipments["delivery_time_minuts"]

0      5640.0
1       120.0
2      3840.0
3      2640.0
4         NaN
        ...
995    4560.0
996    1140.0
997    1020.0
998    4560.0
999    5160.0
Name: delivery_time_minuts, Length: 1000, dtype: float64

In [25]:
# Calculate whether delivery was late:
fact_shipments["is_late"] = (
    fact_shipments["actual_delivery_datetime"]
    > fact_shipments["promised_datetime"]
)

In [26]:
# Delivered flag
fact_shipments["is_delivered"] = (
    fact_shipments["actual_delivery_datetime"].notna()
)

In [27]:
fact_shipments["is_late"]

0       True
1      False
2       True
3       True
4      False
       ...
995     True
996    False
997    False
998     True
999     True
Name: is_late, Length: 1000, dtype: bool

In [28]:
# Calculate delay:
fact_shipments["delay_minutes"] = (
    fact_shipments["actual_delivery_datetime"]
    - fact_shipments["promised_datetime"]
).dt.total_seconds() / 60

In [29]:
fact_shipments["delay_minutes"]

0      1320.0
1      -600.0
2       960.0
3      1920.0
4         NaN
        ...
995     240.0
996    -300.0
997    -420.0
998    1680.0
999     840.0
Name: delay_minutes, Length: 1000, dtype: float64

In [30]:
fact_shipments.loc[
    fact_shipments["actual_delivery_datetime"].isna(),
    "delay_minutes"
] = pd.NA

In [31]:
fact_shipments["delay_minutes"]

0      1320.0
1      -600.0
2       960.0
3      1920.0
4         NaN
        ...
995     240.0
996    -300.0
997    -420.0
998    1680.0
999     840.0
Name: delay_minutes, Length: 1000, dtype: float64

In [32]:
fact_shipments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   shipment_id               1000 non-null   object
 1   order_id                  1000 non-null   object
 2   customer_id               1000 non-null   object
 3   service_type              1000 non-null   object
 4   branch_id                 1000 non-null   object
 5   route_id                  1000 non-null   object
 6   order_datetime            1000 non-null   datetime64[ns]
 7   promised_datetime         1000 non-null   datetime64[ns]
 8   actual_delivery_datetime  833 non-null    datetime64[ns]
 9   status                    1000 non-null   object
 10  weight_kg                 1000 non-null   float64
 11  distance_km_x             1000 non-null   int64
 12  payment_method            1000 non-null   object
 13  delivery_revenue          1000 non-null   float64
 14  priority                  1000 non-null   object
 15  month                     1000 non-null   object
 16  customer_name             1000 non-null   object
 17  industry                  1000 non-null   object
 18  branch_name               1000 non-null   object
 19  city                      1000 non-null   object
 20  route_name                1000 non-null   object
 21  origin_city               1000 non-null   object
 22  destination_city          1000 non-null   object
 23  distance_km_y             1000 non-null   int64
 24  planned_minutes           1000 non-null   int64
 25  delivery_time_minuts      833 non-null    float64
 26  is_late                   1000 non-null   bool
 27  is_delivered              1000 non-null   bool
 28  delay_minutes             833 non-null    float64
dtypes: bool(2), datetime64[ns](3), float64(4), int64(3), object(17)
memory usage: 213.0+ KB

In [33]:
fact_shipments

,shipment_id,order_id,customer_id,service_type,branch_id,route_id,order_datetime,promised_datetime,actual_delivery_datetime,status,...,city,route_name,origin_city,destination_city,distance_km_y,planned_minutes,delivery_time_minuts,is_late,is_delivered,delay_minutes
0,SHP00001,ORD00001,CUST008,Retail,BR004,RT017,2026-01-30 21:13:00,2026-02-02 21:13:00,2026-02-03 19:13:00,Delivered,...,Madinah,Jeddah North,Jeddah,Abha,617,78,5640.0,True,True,1320.0
1,SHP00002,ORD00002,CUST008,Retail,BR001,RT006,2026-06-22 09:46:00,2026-06-22 21:46:00,2026-06-22 11:46:00,Delivered,...,Riyadh,Riyadh South,Makkah,Dammam,380,118,120.0,False,True,-600.0
2,SHP00003,ORD00003,CUST001,E-Commerce,BR006,RT094,2026-08-28 02:59:00,2026-08-30 02:59:00,2026-08-30 18:59:00,Delivered,...,Abha,Riyadh-Jeddah,Jeddah,Madinah,773,73,3840.0,True,True,960.0
3,SHP00004,ORD00004,CUST008,Retail,BR006,RT045,2026-08-11 12:24:00,2026-08-12 00:24:00,2026-08-13 08:24:00,Delivered,...,Abha,Makkah Central,Madinah,Abha,621,80,2640.0,True,True,1920.0
4,SHP00005,ORD00005,CUST009,Retail,BR006,RT093,2026-02-02 23:14:00,2026-02-03 11:14:00,NaT,In Transit,...,Abha,Riyadh East,Makkah,Jeddah,281,81,NaN,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,SHP00996,ORD00996,CUST012,E-Commerce,BR002,RT032,2026-02-19 04:20:00,2026-02-22 04:20:00,2026-02-22 08:20:00,Returned,...,Jeddah,Riyadh-Jeddah,Jeddah,Dammam,757,117,4560.0,True,True,240.0
996,SHP00997,ORD00997,CUST006,Healthcare,BR005,RT094,2026-05-11 03:24:00,2026-05-12 03:24:00,2026-05-11 22:24:00,Delivered,...,Makkah,Riyadh-Jeddah,Jeddah,Madinah,773,73,1140.0,False,True,-300.0
997,SHP00998,ORD00998,CUST013,Healthcare,BR006,RT001,2026-07-17 08:45:00,2026-07-18 08:45:00,2026-07-18 01:45:00,Delivered,...,Abha,Riyadh Central,Jeddah,Madinah,747,90,1020.0,False,True,-420.0
998,SHP00999,ORD00999,CUST009,Retail,BR006,RT025,2026-02-07 08:20:00,2026-02-09 08:20:00,2026-02-10 12:20:00,Returned,...,Abha,Jeddah Central,Makkah,Abha,396,117,4560.0,True,True,1680.0
999,SHP01000,ORD01000,CUST015,E-Commerce,BR001,RT039,2026-02-19 16:51:00,2026-02-22 16:51:00,2026-02-23 06:51:00,Delivered,...,Riyadh,Riyadh Central,Makkah,Riyadh,87,37,5160.0,True,True,840.0

In [34]:
# 2. Save the DataFrame to a CSV file
fact_shipments.to_csv('Transport.csv', index=False)

#  all numeric columns

In [35]:
numeric_df = fact_shipments.select_dtypes(include=["number"])

numeric_df.head()

,weight_kg,distance_km_x,delivery_revenue,distance_km_y,planned_minutes,delivery_time_minuts,delay_minutes
0,53.74,58,100.75,617,78,5640.0,1320.0
1,89.62,594,700.87,380,118,120.0,-600.0
2,22.01,140,204.26,773,73,3840.0,960.0
3,105.01,138,240.95,621,80,2640.0,1920.0
4,117.43,476,506.82,281,81,NaN,NaN

# All Categories Columns

In [36]:
categorical_df = fact_shipments.select_dtypes(
    include=["object", "bool"]
)

categorical_df.head()

,shipment_id,order_id,customer_id,service_type,branch_id,route_id,status,payment_method,priority,month,customer_name,industry,branch_name,city,route_name,origin_city,destination_city,is_late,is_delivered
0,SHP00001,ORD00001,CUST008,Retail,BR004,RT017,Delivered,Cash on Delivery,Same Day,2026-01,Danube,Retail,Madinah Hub,Madinah,Jeddah North,Jeddah,Abha,True,True
1,SHP00002,ORD00002,CUST008,Retail,BR001,RT006,Delivered,Cash on Delivery,Same Day,2026-06,Danube,Retail,Riyadh Central,Riyadh,Riyadh South,Makkah,Dammam,False,True
2,SHP00003,ORD00003,CUST001,E-Commerce,BR006,RT094,Delivered,Cash on Delivery,Express,2026-08,Noon,E-Commerce,Abha Hub,Abha,Riyadh-Jeddah,Jeddah,Madinah,True,True
3,SHP00004,ORD00004,CUST008,Retail,BR006,RT045,Delivered,Prepaid,Express,2026-08,Danube,Retail,Abha Hub,Abha,Makkah Central,Madinah,Abha,True,True
4,SHP00005,ORD00005,CUST009,Retail,BR006,RT093,In Transit,Account,Standard,2026-02,Lulu Hypermarket,Retail,Abha Hub,Abha,Riyadh East,Makkah,Jeddah,False,False

In [37]:
# Numerical data
numeric_df = fact_shipments.select_dtypes(include=["number"])

# Categorical data
categorical_df = fact_shipments.select_dtypes(include=["object", "bool"])

# Datetime data
datetime_df = fact_shipments.select_dtypes(include=["datetime"])

In [38]:
print("Numeric:", numeric_df.columns.tolist())

Numeric: ['weight_kg', 'distance_km_x', 'delivery_revenue', 'distance_km_y', 'planned_minutes', 'delivery_time_minuts', 'delay_minutes']

In [39]:
categorical_df.columns.tolist()

['shipment_id',
 'order_id',
 'customer_id',
 'service_type',
 'branch_id',
 'route_id',
 'status',
 'payment_method',
 'priority',
 'month',
 'customer_name',
 'industry',
 'branch_name',
 'city',
 'route_name',
 'origin_city',
 'destination_city',
 'is_late',
 'is_delivered']

In [40]:
print("Datetime:", datetime_df.columns.tolist())

Datetime: ['order_datetime', 'promised_datetime', 'actual_delivery_datetime']

# Data Quality Analysis ⭐⭐⭐

In [41]:
data_quality = pd.DataFrame({
    "column": fact_shipments.columns,
    "dtype": fact_shipments.dtypes.astype(str).values,
    "missing": fact_shipments.isna().sum().values,
    "unique": fact_shipments.nunique().values
})

data_quality["missing_%"] = (
    data_quality["missing"]
    / len(fact_shipments)
    * 100
)

data_quality

                      column           dtype  missing  unique  missing_%
0                shipment_id          object        0    1000        0.0
1                   order_id          object        0    1000        0.0
2                customer_id          object        0      15        0.0
3               service_type          object        0       3        0.0
4                  branch_id          object        0       6        0.0
5                   route_id          object        0     100        0.0
6             order_datetime  datetime64[ns]        0    1000        0.0
7          promised_datetime  datetime64[ns]        0     998        0.0
8   actual_delivery_datetime  datetime64[ns]      167     833       16.7
9                     status          object        0       6        0.0
10                 weight_kg         float64        0     951        0.0
11             distance_km_x           int64        0     587        0.0
12            payment_method          object        0       3        0.0
13          delivery_revenue         float64        0     997        0.0
14                  priority          object        0       4        0.0
15                     month          object        0       8        0.0
16             customer_name          object        0      15        0.0
17                  industry          object        0       3        0.0
18               branch_name          object        0       6        0.0
19                      city          object        0       6        0.0
20                route_name          object        0      15        0.0
21               origin_city          object        0       6        0.0
22          destination_city          object        0       6        0.0
23             distance_km_y           int64        0      94        0.0
24           planned_minutes           int64        0      59        0.0
25      delivery_time_minuts         float64      167     104       16.7
26                   is_late            bool        0       2        0.0
27              is_delivered            bool        0       2        0.0
28             delay_minutes         float64      167      47       16.7

In [42]:
print(
    "Duplicate rows:",
    fact_shipments.duplicated().sum()
)

Duplicate rows: 0

In [43]:
duplicate_shipments = (
    fact_shipments[
        fact_shipments.duplicated(
            "shipment_id",
            keep=False
        )
    ]
    .sort_values("shipment_id")
)

duplicate_shipments

Empty DataFrame
Columns: [shipment_id, order_id, customer_id, service_type, branch_id, route_id, order_datetime, promised_datetime, actual_delivery_datetime, status, weight_kg, distance_km_x, payment_method, delivery_revenue, priority, month, customer_name, industry, branch_name, city, route_name, origin_city, destination_city, distance_km_y, planned_minutes, delivery_time_minuts, is_late, is_delivered, delay_minutes]
Index: []

[0 rows x 29 columns]

# KPI: Revenue per KM

In [44]:
fact_shipments["revenue_per_km"] = (
    fact_shipments["delivery_revenue"]
    / fact_shipments["distance_km_x"].replace(0, np.nan)
)

In [45]:
print(
    "Average Revenue per KM:",
    fact_shipments["revenue_per_km"].mean().round(2)
)

Average Revenue per KM: 1.36

In [46]:
revenue_per_km_service = (
    fact_shipments
    .groupby("service_type", as_index=False)
    .agg(
        avg_revenue_per_km=("revenue_per_km", "mean"),
        shipments=("shipment_id", "nunique"),
        revenue=("delivery_revenue", "sum")
    )
    .sort_values(
        "avg_revenue_per_km",
        ascending=False
    )
)

revenue_per_km_service

  service_type  avg_revenue_per_km  shipments    revenue
2       Retail            1.426869        411  190711.49
0   E-Commerce            1.342110        333  151463.33
1   Healthcare            1.272552        256  120024.09

# Top management KPIs

In [47]:
total_shipments = len(fact_shipments)

delivered_shipments = fact_shipments["is_delivered"].sum()

undelivered_shipments = (
    total_shipments - delivered_shipments
)

total_revenue = fact_shipments["delivery_revenue"].sum()

avg_revenue_per_shipment = (
    total_revenue / total_shipments
    if total_shipments > 0 else 0
)

delivery_success_rate = (
    delivered_shipments / total_shipments * 100
    if total_shipments > 0 else 0
)

delivered_df = fact_shipments[
    fact_shipments["is_delivered"]
]

on_time_shipments = (
    ~delivered_df["is_late"]
).sum()

on_time_rate = (
    on_time_shipments / len(delivered_df) * 100
    if len(delivered_df) > 0 else 0
)

late_shipments = (
    delivered_df["is_late"].sum()
)

late_rate = (
    late_shipments / len(delivered_df) * 100
    if len(delivered_df) > 0 else 0
)

avg_weight = fact_shipments["weight_kg"].mean()

avg_distance = fact_shipments["distance_km_x"].mean()

avg_delay = delivered_df["delay_minutes"].mean()

In [48]:
kpis = {
    "Total Shipments": f"{total_shipments:,}",
    "Delivered": f"{delivered_shipments:,}",
    "Undelivered": f"{undelivered_shipments:,}",
    "Total Revenue": f"{total_revenue:,.2f}",
    "Revenue / Shipment": f"{avg_revenue_per_shipment:,.2f}",
    "Delivery Success": f"{delivery_success_rate:.1f}%",
    "On-Time Delivery": f"{on_time_rate:.1f}%",
    "Late Delivery": f"{late_rate:.1f}%",
  "Avg Weight": f"{avg_weight:,.1f} kg",
    "Avg Distance": f"{avg_distance:,.1f} km",
    "Avg Delay": f"{avg_delay:,.1f} min"
}



kpis

{'Total Shipments': '1,000',
 'Delivered': '833',
 'Undelivered': '167',
 'Total Revenue': '462,198.91',
 'Revenue / Shipment': '462.20',
 'Delivery Success': '83.3%',
 'On-Time Delivery': '29.8%',
 'Late Delivery': '70.2%',
 'Avg Weight': '60.1 kg',
 'Avg Distance': '423.9 km',
 'Avg Delay': '729.1 min'}

In [49]:
import pandas as pd
import numpy as np
import plotly.express as px

numeric_cols = [
    "weight_kg",
    "distance_km_x",
    "delivery_revenue",
    "distance_km_y",
    "planned_minutes",
    "delivery_time_minuts",
    "delay_minutes"
]

corr = fact_shipments[numeric_cols].corr()

corr

,weight_kg,distance_km_x,delivery_revenue,distance_km_y,planned_minutes,delivery_time_minuts,delay_minutes
weight_kg,1.000000,0.004813,0.059657,-0.003439,0.059271,0.019095,0.020606
distance_km_x,0.004813,1.000000,0.962491,0.018915,-0.021749,0.024089,-0.020682
delivery_revenue,0.059657,0.962491,1.000000,0.022878,-0.016221,0.007244,-0.023631
distance_km_y,-0.003439,0.018915,0.022878,1.000000,-0.039699,-0.003873,-0.041286
planned_minutes,0.059271,-0.021749,-0.016221,-0.039699,1.000000,0.009990,0.005479
delivery_time_minuts,0.019095,0.024089,0.007244,-0.003873,0.009990,1.000000,0.541482
delay_minutes,0.020606,-0.020682,-0.023631,-0.041286,0.005479,0.541482,1.000000

In [50]:
fig = px.imshow(
    corr,
    text_auto=".2f",
    aspect="auto",
    title="Correlation Matrix — Shipment Performance",
    labels=dict(
        x="Variables",
        y="Variables",
        color="Correlation"
    )
)

fig.update_layout(
    width=1000,
    height=750
)

fig.show()

In [51]:

import plotly.express as px
import plotly.graph_objects as go

from IPython.display import display, HTML

In [52]:
kpi_html = ""

for name, value in kpis.items():
    kpi_html += f"""
    <div style="
        display:inline-block;
        width:180px;
        min-height:100px;
        margin:8px;
        padding:18px;
        border-radius:12px;
        background:#ffffff;
        box-shadow:0 3px 12px rgba(0,0,0,0.12);
        text-align:center;
        vertical-align:top;
    ">
        <div style="
            font-size:14px;
            color:#666;
            margin-bottom:10px;
        ">
            {name}
        </div>

        <div style="
            font-size:24px;
            font-weight:bold;
            color:#17365D;
        ">
            {value}
        </div>
    </div>
    """

display(HTML(kpi_html))

#  Monthly Business Performance ⭐⭐⭐

In [53]:
monthly_analysis = (
    fact_shipments
    .groupby("month", as_index=False)
    .agg(
        shipments=("shipment_id", "nunique"),
        revenue=("delivery_revenue", "sum"),
        avg_revenue=("delivery_revenue", "mean"),
        total_weight=("weight_kg", "sum"),
        avg_distance=("distance_km_x", "mean"),
        avg_delay=("delay_minutes", "mean")
    )
    .sort_values("month")
)

monthly_analysis

,month,shipments,revenue,avg_revenue,total_weight,avg_distance,avg_delay
0,2026-01,132,62957.24,476.948788,7972.98,438.545455,758.181818
1,2026-02,122,54382.02,445.754262,8347.77,399.713115,829.591837
2,2026-03,124,52139.00,420.475806,7067.18,383.475806,737.475728
3,2026-04,130,61682.27,474.479000,7641.11,430.146154,865.714286
4,2026-05,108,52552.19,486.594352,6581.44,459.592593,683.333333
5,2026-06,150,70862.13,472.414200,8974.09,432.253333,640.312500
6,2026-07,116,52021.02,448.457069,6946.63,414.008621,598.181818
7,2026-08,118,55603.04,471.212203,6570.56,434.533898,731.400000

# EDA Graph

In [54]:
status_count = (
    fact_shipments["status"]
    .value_counts()
    .reset_index()
)

status_count.columns = [
    "status",
    "shipments"
]

fig = px.bar(
    status_count,
    x="status",
    y="shipments",
    title="Shipment Status Distribution",
    text="shipments"
)

fig.update_traces(
    textposition="outside"
)

fig.show()

# Shipments by Service Type

In [55]:
service_summary = (
    fact_shipments
    .groupby("service_type")
    .agg(
        shipments=("shipment_id", "count"),
        revenue=("delivery_revenue", "sum")
    )
    .reset_index()
)

fig = px.bar(
    service_summary,
    x="service_type",
    y="shipments",
    title="Shipments by Service Type",
    text="shipments"
)

fig.show()

# Revenue by Service Type

In [56]:
fig = px.bar(
    service_summary,
    x="service_type",
    y="revenue",
    title="Revenue by Service Type",
    text="revenue"
)

fig.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside"
)

fig.show()

# Top 10 Customers

In [57]:
top_customers = (
    fact_shipments
    .groupby("customer_name")
    .agg(
        shipments=("shipment_id", "count"),
        revenue=("delivery_revenue", "sum")
    )
    .reset_index()
    .sort_values(
        "revenue",
        ascending=False
    )
    .head(10)
)

fig = px.bar(
    top_customers.sort_values("revenue"),
    x="revenue",
    y="customer_name",
    orientation="h",
    title="Top 10 Customers by Revenue",
    text="revenue"
)

fig.update_traces(
    texttemplate="%{text:,.0f}"
)

fig.show()

# Top 10 Routes

In [58]:
top_routes = (
    fact_shipments
    .groupby("route_name")
    .agg(
        shipments=("shipment_id", "count"),
        revenue=("delivery_revenue", "sum"),
        avg_distance=("distance_km_x", "mean")
    )
    .reset_index()
    .sort_values(
        "shipments",
        ascending=False
    )
    .head(10)
)

fig = px.bar(
    top_routes.sort_values("shipments"),
    x="shipments",
    y="route_name",
    orientation="h",
    title="Top 10 Routes by Shipment Volume",
    text="shipments"
)

fig.show()

In [59]:
top_branches = (
    fact_shipments
    .groupby("branch_name")
    .agg(
        shipments=("shipment_id", "count"),
        revenue=("delivery_revenue", "sum")
    )
    .reset_index()
    .sort_values(
        "shipments",
        ascending=False
    )
    .head(10)
)

fig = px.bar(
    top_branches.sort_values("shipments"),
    x="shipments",
    y="branch_name",
    orientation="h",
    title="Top Branches by Shipment Volume",
    text="shipments"
)

fig.show()

# Revenue by Service Type

In [60]:
fig = px.bar(
    service_summary,
    x="service_type",
    y="revenue",
    title="Revenue by Service Type",
    text="revenue"
)

fig.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside"
)

fig.show()

# Top 10 Customers by Revenue ⭐

In [61]:
top_customers_revenue = (
    fact_shipments
    .groupby(["customer_id", "customer_name"], as_index=False)
    .agg(
        shipments=("shipment_id", "nunique"),
        revenue=("delivery_revenue", "sum"),
        avg_revenue=("delivery_revenue", "mean"),
        total_weight=("weight_kg", "sum"),
        avg_distance=("distance_km_x", "mean")
    )
    .sort_values("revenue", ascending=False)
    .head(10)
)

top_customers_revenue

,customer_id,customer_name,shipments,revenue,avg_revenue,total_weight,avg_distance
4,CUST005,Nahdi Medical,77,37294.78,484.347792,4333.41,431.649351
7,CUST008,Danube,73,36112.63,494.693562,4426.53,449.575342
11,CUST012,HungerStation,79,35246.80,446.162025,4377.52,409.101266
9,CUST010,BinDawood,76,34109.15,448.804605,4337.30,416.302632
3,CUST004,Extra Stores,80,33935.15,424.189375,5376.43,394.575000
1,CUST002,Amazon Saudi,68,32463.58,477.405588,3937.59,446.750000
6,CUST007,SACO,57,31177.08,546.966316,3380.24,508.315789
0,CUST001,Noon,67,30092.70,449.144776,4291.57,417.328358
5,CUST006,Al-Dawaa Pharmacies,65,28722.65,441.886923,3549.84,410.246154
2,CUST003,Jarir Bookstore,63,28607.82,454.092381,3883.28,397.253968

# Monthly Shipment Trend

In [62]:
monthly_analysis["revenue_growth_%"] = (
    monthly_analysis["revenue"]
    .pct_change()
    .mul(100)
)

monthly_analysis["shipment_growth_%"] = (
    monthly_analysis["shipments"]
    .pct_change()
    .mul(100)
)

monthly_analysis

,month,shipments,revenue,avg_revenue,total_weight,avg_distance,avg_delay,revenue_growth_%,shipment_growth_%
0,2026-01,132,62957.24,476.948788,7972.98,438.545455,758.181818,NaN,NaN
1,2026-02,122,54382.02,445.754262,8347.77,399.713115,829.591837,-13.620705,-7.575758
2,2026-03,124,52139.00,420.475806,7067.18,383.475806,737.475728,-4.124562,1.639344
3,2026-04,130,61682.27,474.479000,7641.11,430.146154,865.714286,18.303516,4.838710
4,2026-05,108,52552.19,486.594352,6581.44,459.592593,683.333333,-14.801790,-16.923077
5,2026-06,150,70862.13,472.414200,8974.09,432.253333,640.312500,34.841440,38.888889
6,2026-07,116,52021.02,448.457069,6946.63,414.008621,598.181818,-26.588405,-22.666667
7,2026-08,118,55603.04,471.212203,6570.56,434.533898,731.400000,6.885717,1.724138

# Weight Distribution

In [63]:
fig = px.histogram(
    fact_shipments,
    x="weight_kg",
    nbins=30,
    title="Shipment Weight Distribution",
    marginal="box"
)

fig.show()

# Distance vs Revenue

In [64]:
fig = px.scatter(
    fact_shipments,
    x="distance_km_x",
    y="delivery_revenue",
    color="service_type",
    hover_data=[
        "shipment_id",
        "customer_name",
        "route_name",
        "weight_kg"
    ],
    title="Distance vs Delivery Revenue"
)

fig.show()

In [65]:
delivery_performance = (
    delivered_df["is_late"]
    .map({
        False: "On Time",
        True: "Late"
    })
    .value_counts()
    .reset_index()
)

delivery_performance.columns = [
    "delivery_status",
    "shipments"
]

fig = px.pie(
    delivery_performance,
    names="delivery_status",
    values="shipments",
    title="On-Time vs Late Deliveries",
    hole=0.45
)

fig.show()

In [66]:
late_by_service = (
    delivered_df
    .groupby("service_type")
    .agg(
        delivered=("shipment_id", "count"),
        late_shipments=("is_late", "sum")
    )
    .reset_index()
)

late_by_service["late_rate"] = (
    late_by_service["late_shipments"]
    / late_by_service["delivered"]
    * 100
)

fig = px.bar(
    late_by_service.sort_values("late_rate"),
    x="service_type",
    y="late_rate",
    title="Late Delivery Rate by Service Type",
    text="late_rate"
)

fig.update_traces(
    texttemplate="%{text:.1f}%"
)

fig.show()

In [67]:
late_by_branch = (
    delivered_df
    .groupby("branch_name")
    .agg(
        delivered=("shipment_id", "count"),
        late_shipments=("is_late", "sum")
    )
    .reset_index()
)

late_by_branch["late_rate"] = (
    late_by_branch["late_shipments"]
    / late_by_branch["delivered"]
    * 100
)

fig = px.bar(
    late_by_branch.sort_values("late_rate"),
    x="late_rate",
    y="branch_name",
    orientation="h",
    title="Late Delivery Rate by Branch",
    text="late_rate"
)

fig.update_traces(
    texttemplate="%{text:.1f}%"
)

fig.show()